### ISSUE TITLE
Connection was lost. Restarting engine...

### ISSUE THREAD

**Issue by jenglich-bgh** [diegogarciahuerta/tk-substancepainter#10]
The Integration isn't working for me. Im getting the log-message:
`
[Plugin - shotgun_bridge] Shotgun engine | Shotgun Substance Painter Engine connection was lost. Restarting engine...`

I'm using: 

- substancepainter engine v1.2.1
- framework-unrealqt v1.0.0
- Substance Painter 2020.1.2

I know the engine is only tested for 2019 but i wanted to make sure if the error i'm getting
occures because of my SP version or if I'm doing something wrong here.

EDIT: Oh in another issue it says that the engine is tested on 2020. :/

Sincerely 
Jonas

**Comment by jenglich-bgh** [comment]
In the log files i found only one line that could probably help me out here:

 [2796 DEBUG sgtk.core.util.qt_importer] Unable to import module 'QtWebKit': No module named QtWebKitWidgets

Could that be the reason for the reconnecting?

**Comment by diegogarciahuerta** [comment]
Do you mind testing the the release  **v1.2.2** as it covers 2020.1.x+ support. A new versioning system was introduced from Substance Painter version 2020.1, this version became version 6.1. This basically broke compatibility and the engine had to be updated for this reason.
https://github.com/diegogarciahuerta/tk-substancepainter/releases

Please let me know if this fixes your issue.

**Comment by jenglich-bgh** [comment]
Thanks that  fixed the issue
