### ISSUE TITLE
Could not read templates configuration

### ISSUE THREAD

**Issue by jfobrien87** [diegogarciahuerta/tk-substancepainter#5]
Hi Diego,

I'm trying to test out your substance integration as my team are planning to move our project and asset management over to a shotgun/perforce pipeline very soon but I have been getting errors whenever I try to cache_apps:

ERROR: Could not read templates configuration: Could not open file
'D:\Shotgun\configs\jfo_test_project\config\core\templates.yml'. Error
reported: 'while scanning for the next token found character '\t' that cannot
start any token   in
"D:\Shotgun\configs\jfo_test_project\config\core\templates.yml", line 60,
column 1'

Line 60 is where I have copied the keys code in from the templates file in the repo. If I remove that line I seem to just get the same error for the other lines I've added from the repo versions of the yml files.

Any chance you can help me out? I'm new to shotgun but will be one of our admins moving forward.

Cheers,
John

**Comment by diegogarciahuerta** [comment]
Hi John,
There is definitely either some syntax error in your templates.yml or might be that you did not merged all the yaml files listed here: 
[configuration additions](https://github.com/diegogarciahuerta/tk-substancepainter/tree/master/config)

**Note that you actually have to MERGE the contents**, not replace it, follow the example for the asset_step.yml file listed in my documentation:
[Modifying the toolkit configuration files to add this engine and related apps](https://github.com/diegogarciahuerta/tk-substancepainter#modifying-the-toolkit-configuration-files-to-add-this-engine-and-related-apps)

Would you mind checking if this is the case and get back to me, please ? I have several studios using the integration and so far none has reported anything related to the configs.

This is a video where Shotgun engineers explain how those YAML files really work, in case it helps (warning, it is technical)
[Shotgun Toolkit Webinar: Demystifying the New Default Configuration](https://youtu.be/eKHaC1dZCeE)

Cheers,
Diego

**Comment by diegogarciahuerta** [comment]
I was wondering if you got any luck with the templates,

Cheers

- Diego

**Comment by jfobrien87** [comment]
Hi Diego,

Sorry for the late reply - crazy times.

We have integrated shotgun into production but for now we aren't using any
toolkit integrations and just running via the web interface as we are quite
a small team and most of our work is already shared via source control for
our Unity projects (perforce). So at this stage we don't have need for the
substance integration so I haven't spent any more time on it. Please feel
free to close the issue on github and if we need the integration on our end
in future and we still get stuck I'll reach out to you.

Cheers,
John

**Comment by diegogarciahuerta** [comment]
Thanks John!
