### ISSUE TITLE
2020 versioning changes

### ISSUE THREAD

**Issue by jhultgre** [diegogarciahuerta/tk-substancepainter#7]
Substance painter went from version 2019.3.3 to version 6.1.0.
That breaks the minimum version check.

**Comment by MrDice** [comment]
It's part of the official release notes (https://docs.substance3d.com/spdoc/version-2020-1-6-1-0-194216357.html). A simple approach may be the replacement of the years (2017.x -> 3.x; 2018.x -> 4.x; 2019.x -> 5.x; 2020.x -> 6.x). We are currently implementing it for us. If it works I can maybe share it here as a pull request.

**Comment by diegogarciahuerta** [comment]
FYI, I have a fix on it's way, I got distracted with playing with the new Python API...

**Comment by diegogarciahuerta** [comment]
Would anyone be able to test the pull request #9 . I tested myself with the versions I had at hand and seems to work:
6.1.0 (new versioning system)
2019.2.3 (old versioning system)
2017.1.0 (old versioning system, and not supported by the engine, ie. older than 2018.3)

**Comment by diegogarciahuerta** [comment]
Closing issue, resolved in release [1.2.2](https://github.com/diegogarciahuerta/tk-substancepainter/releases/tag/v1.2.2)
Thanks @MrDice for pointing out this issue!
